In [1]:
#线性回归简易版
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

In [2]:
true_w=torch.tensor([2,-3.4])
true_b=4.2
features,labels = d2l.synthetic_data(true_w,true_b,1000)

In [3]:
def load_array(data_arrays,batch_size,is_train=True):
    dataset=data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset,batch_size,shuffle=is_train)

In [4]:
batch_size=10
data_iter=load_array((features,labels),batch_size)

In [5]:
next(iter(data_iter))

[tensor([[-1.1702,  0.2287],
         [-0.3590, -1.3070],
         [ 1.0642,  0.1985],
         [ 0.1388, -0.8712],
         [ 0.2301, -0.6523],
         [-0.4848, -0.5358],
         [ 0.2097,  0.8577],
         [-0.7690,  0.2573],
         [ 1.4455,  0.5006],
         [ 1.6871, -0.1853]]),
 tensor([[1.0790],
         [7.9105],
         [5.6690],
         [7.4423],
         [6.8800],
         [5.0456],
         [1.6777],
         [1.7930],
         [5.3884],
         [8.2168]])]

In [7]:
from torch import nn

net = nn.Sequential(nn.Linear(2, 1))

In [8]:
net[0].weight.data.normal_(0,0.01)

tensor([[0.0083, 0.0047]])

In [9]:
net[0].bias.data.fill_(0)

tensor([0.])

In [10]:
loss=nn.MSELoss()

In [11]:
trainer=torch.optim.SGD(net.parameters(),lr=0.3)

In [12]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X) ,y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000124
epoch 2, loss 0.000116
epoch 3, loss 0.000124


In [13]:
w = net[0].weight.data
print('w的估计误差：', true_w - w.reshape(true_w.shape))
b = net[0].bias.data
print('b的估计误差：', true_b - b)

w的估计误差： tensor([ 0.0022, -0.0026])
b的估计误差： tensor([-0.0012])
